name: Update Release Notes

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write   # 🔑 даём право писать в репозиторий

jobs:
  update-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run make_release.py
        run: |
          python3 scripts/make_release.py
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add RELEASE_NOTES.md .version
          git commit -m "chore: update release notes [skip ci]" || echo "No changes to commit"
          git push

